// This file is auto-generated by src/avr/maintain-protocol script! DON'T EDIT!

export const avrProtocolVersion = 0xda;

export interface AvrData {
}

export function asAvrData(vals: {[id: string]: number}): AvrData { return {
};}

